FROM python:3.10

EXPOSE 80
EXPOSE 443
EXPOSE 8080
EXPOSE 8000

ENV API_KEY='OPENAI_API_KEY'

RUN mkdir static
RUN mkdir templates
ADD app.py .
ADD auth_keys.db .
ADD requirements.txt .
ADD .env .
ADD README.md .
COPY static /static/
COPY templates /templates/

RUN apt update && apt upgrade -y
RUN apt install nmap -y
RUN pip install -r requirements.txt

RUN echo "API_KEY = '${API_KEY}'" >> .env

CMD [ "sh", "-c","python ./app.py" ]